// Données draft 2026 (projection / recherchées).
//
// ROOKIE_SCALE_2026 : salaire année 1 (à 120 %, ce que touchent réellement la
// plupart des 1ers tours) pour les choix 1 → 30, saison 2026-27. Base = barème
// officiel 2025-26 (Hoops Rumors) projeté +5 % (le barème grandit avec le cap).
// Index 1..30.
export const ROOKIE_SCALE_2026 = {
  1: 14_517_000, 2: 12_989_000, 3: 11_664_000, 4: 10_516_000, 5: 9_523_000,
  6: 8_650_000, 7: 7_896_000, 8: 7_234_000, 9: 6_649_000, 10: 6_317_000,
  11: 6_001_000, 12: 5_701_000, 13: 5_416_000, 14: 5_145_000, 15: 4_888_000,
  16: 4_643_000, 17: 4_411_000, 18: 4_191_000, 19: 4_002_000, 20: 3_842_000,
  21: 3_688_000, 22: 3_541_000, 23: 3_399_000, 24: 3_264_000, 25: 3_132_000,
  26: 3_029_000, 27: 2_941_000, 28: 2_923_000, 29: 2_902_000, 30: 2_881_000,
};

// Ordre de draft réel 2026 (mock ESPN post-combine, loterie de mai 2026
// intégrée, picks échangés inclus) : quelle franchise pioche à chaque slot.
// `team` = abréviation de l'équipe qui détient le choix.
export const DRAFT_ORDER_2026 = [
  { pick: 1, team: 'WAS' }, { pick: 2, team: 'UTA' }, { pick: 3, team: 'MEM' }, { pick: 4, team: 'CHI' },
  { pick: 5, team: 'LAC' }, { pick: 6, team: 'BRK' }, { pick: 7, team: 'SAC' }, { pick: 8, team: 'ATL' },
  { pick: 9, team: 'DAL' }, { pick: 10, team: 'MIL' }, { pick: 11, team: 'GSW' }, { pick: 12, team: 'OKC' },
  { pick: 13, team: 'MIA' }, { pick: 14, team: 'CHO' }, { pick: 15, team: 'CHI' }, { pick: 16, team: 'MEM' },
  { pick: 17, team: 'OKC' }, { pick: 18, team: 'CHO' }, { pick: 19, team: 'TOR' }, { pick: 20, team: 'SAS' },
  { pick: 21, team: 'DET' }, { pick: 22, team: 'PHI' }, { pick: 23, team: 'ATL' }, { pick: 24, team: 'NYK' },
  { pick: 25, team: 'LAL' }, { pick: 26, team: 'DEN' }, { pick: 27, team: 'BOS' }, { pick: 28, team: 'MIN' },
  { pick: 29, team: 'CLE' }, { pick: 30, team: 'DAL' },
  { pick: 31, team: 'NYK' }, { pick: 32, team: 'MEM' }, { pick: 33, team: 'BRK' }, { pick: 34, team: 'SAC' },
  { pick: 35, team: 'SAS' }, { pick: 36, team: 'LAC' }, { pick: 37, team: 'OKC' }, { pick: 38, team: 'CHI' },
  { pick: 39, team: 'HOU' }, { pick: 40, team: 'BOS' }, { pick: 41, team: 'MIA' }, { pick: 42, team: 'SAS' },
  { pick: 43, team: 'BRK' }, { pick: 44, team: 'SAS' }, { pick: 45, team: 'SAC' }, { pick: 46, team: 'ORL' },
  { pick: 47, team: 'PHO' }, { pick: 48, team: 'DAL' }, { pick: 49, team: 'DEN' }, { pick: 50, team: 'TOR' },
  { pick: 51, team: 'WAS' }, { pick: 52, team: 'LAC' }, { pick: 53, team: 'HOU' }, { pick: 54, team: 'GSW' },
  { pick: 55, team: 'NYK' }, { pick: 56, team: 'CHI' }, { pick: 57, team: 'ATL' }, { pick: 58, team: 'NOP' },
  { pick: 59, team: 'MIN' }, { pick: 60, team: 'WAS' },
];

// Classe de prospects 2026 (mock ESPN post-combine, 2 tours = 60 choix).
// `rank` = slot projeté. ht (pouces) / wt (lbs) / age : mesures Tankathon
// post-combine. note : scouting (ESPN top 30). Champs détail absents = inconnus.
export const PROSPECTS_2026 = [
  { rank: 1, name: 'AJ Dybantsa', pos: 'SF', team: 'BYU', ht: 82, wt: 217, age: 19, note: 'Ailier scoreur avec de la taille ; tir et dribble à affiner.' },
  { rank: 2, name: 'Darryn Peterson', pos: 'SG', team: 'Kansas', ht: 78, wt: 199, age: 19, note: "Scoreur d'élite, création de tir rare." },
  { rank: 3, name: 'Cameron Boozer', pos: 'PF', team: 'Duke', ht: 82, wt: 253, age: 18, note: 'Ailier-fort prêt pour la NBA, lecture du jeu et spacing excellents.' },
  { rank: 4, name: 'Caleb Wilson', pos: 'PF', team: 'North Carolina', ht: 83, wt: 211, age: 19, note: "Ailier à fort potentiel, outils physiques d'élite, irrégulier." },
  { rank: 5, name: 'Keaton Wagler', pos: 'SG', team: 'Illinois', ht: 78, wt: 188, age: 19, note: 'Grand meneur-créateur, vision et spacing.' },
  { rank: 6, name: 'Darius Acuff Jr.', pos: 'PG', team: 'Arkansas', ht: 75, wt: 186, age: 19, note: "Scoreur d'élite aux trois niveaux, peu de pertes de balle." },
  { rank: 7, name: 'Kingston Flemings', pos: 'PG', team: 'Houston', ht: 76, wt: 183, age: 19, note: 'Meneur explosif, tir en progrès, gros intangibles.' },
  { rank: 8, name: 'Aday Mara', pos: 'C', team: 'Michigan', ht: 88, wt: 260, age: 21, note: "Pivot 7'4 au playmaking, finition et protection de cercle rares." },
  { rank: 9, name: 'Mikel Brown Jr.', pos: 'PG', team: 'Louisville', ht: 77, wt: 190, age: 20, note: 'Meneur de format NBA, shoot et vision.' },
  { rank: 10, name: 'Nate Ament', pos: 'SF', team: 'Tennessee', ht: 83, wt: 211, age: 19, note: "Ailier longiligne, taille/envergure d'élite, à l'aise balle en main." },
  { rank: 11, name: 'Brayden Burries', pos: 'SG', team: 'Arizona', ht: 77, wt: 215, age: 20, note: 'Ailier explosif, shoot et rebond.' },
  { rank: 12, name: 'Yaxel Lendeborg', pos: 'PF', team: 'Michigan', ht: 82, wt: 241, age: 23, note: 'Intérieur polyvalent, skills extérieurs, défense multi-postes.' },
  { rank: 13, name: 'Labaron Philon Jr.', pos: 'PG', team: 'Alabama', ht: 76, wt: 176, age: 20, note: 'Meneur-scoreur créatif, handle serré ; profil 6e homme.' },
  { rank: 14, name: 'Karim Lopez', pos: 'SF', team: 'NZ Breakers', ht: 82, wt: 222, age: 19, note: 'Ailier taille/skill/combativité ; tir à développer.' },
  { rank: 15, name: 'Cameron Carr', pos: 'SG', team: 'Baylor', ht: 78, wt: 184, age: 21, note: "Explosivité + adresse, athlétisme d'élite." },
  { rank: 16, name: 'Christian Anderson', pos: 'PG', team: 'Texas Tech', ht: 74, wt: 180, age: 20, note: 'Shooteur 3 pts d\'élite (41.5%), jeu sur écran.' },
  { rank: 17, name: 'Morez Johnson Jr.', pos: 'PF', team: 'Michigan', ht: 82, wt: 251, age: 20, note: 'Intérieur mobile, polyvalence défensive.' },
  { rank: 18, name: 'Hannes Steinbach', pos: 'PF', team: 'Washington', ht: 84, wt: 248, age: 20, note: "Rebondeur d'élite, instinct, tir." },
  { rank: 19, name: 'Bennett Stirtz', pos: 'PG', team: 'Iowa', ht: 76, wt: 186, age: 22, note: 'Shooteur prêt à jouer, gravité, pose des écrans.' },
  { rank: 20, name: 'Jayden Quaintance', pos: 'C', team: 'Kentucky', ht: 82, wt: 253, age: 18, note: 'Excellent profil défensif, gabarit, contres.' },
  { rank: 21, name: 'Isaiah Evans', pos: 'SG', team: 'Duke', ht: 79, wt: 186, age: 20, note: 'Shooteur extérieur, taille, manque de coffre.' },
  { rank: 22, name: 'Allen Graves', pos: 'PF', team: 'Santa Clara', ht: 81, wt: 226, age: 19, note: 'Profil analytics solide, sens du jeu gagnant.' },
  { rank: 23, name: 'Ebuka Okorie', pos: 'PG', team: 'Stanford', ht: 75, wt: 186, age: 19, note: 'Jeune meneur prometteur.' },
  { rank: 24, name: 'Chris Cenac Jr.', pos: 'C', team: 'Houston', ht: 84, wt: 240, age: 19, note: 'Intérieur projetable, taille/mobilité, tir en développement.' },
  { rank: 25, name: 'Henri Veesaar', pos: 'C', team: 'North Carolina', ht: 85, wt: 227, age: 22, note: 'Pivot européen, taille et potentiel au tir.' },
  { rank: 26, name: 'Dailyn Swain', pos: 'SF', team: 'Texas', ht: 80, wt: 211, age: 20, note: 'Ailier athlétique, polyvalence défensive ; 3 pts à développer.' },
  { rank: 27, name: 'Koa Peat', pos: 'PF', team: 'Arizona', ht: 80, wt: 245, age: 19, note: 'Ailier-fort gagnant et défensif, physique ; tir incertain.' },
  { rank: 28, name: 'Meleek Thomas', pos: 'SG', team: 'Arkansas', ht: 76, wt: 190, age: 19, note: 'Scoreur extérieur avec création.' },
  { rank: 29, name: 'Zuby Ejiofor', pos: 'C', team: "St. John's", ht: 81, wt: 245, age: 22, note: 'Intérieur taille/athlétisme.' },
  { rank: 30, name: 'Joshua Jefferson', pos: 'SF', team: 'Iowa State', ht: 81, wt: 246, age: 22 },
  { rank: 31, name: 'Alex Karaban', pos: 'SF', team: 'UConn', ht: 80, wt: 225, age: 23, note: 'Ailier vétéran, pedigree gagnant.' },
  { rank: 32, name: 'Amari Allen', pos: 'SF', team: 'Alabama' },
  { rank: 33, name: 'Matt Able', pos: 'SF', team: 'NC State' },
  { rank: 34, name: 'Tounde Yessoufou', pos: 'SF', team: 'Baylor' },
  { rank: 35, name: 'Tyler Tanner', pos: 'PG', team: 'Vanderbilt' },
  { rank: 36, name: 'Malachi Moreno', pos: 'C', team: 'Kentucky' },
  { rank: 37, name: 'Tarris Reed Jr.', pos: 'C', team: 'UConn', ht: 83, wt: 264, age: 22 },
  { rank: 38, name: 'Milan Momcilovic', pos: 'PF', team: 'Iowa State' },
  { rank: 39, name: 'Luigi Suigo', pos: 'C', team: 'Mega Basket', ht: 88, wt: 289, age: 19 },
  { rank: 40, name: 'Jack Kayil', pos: 'PG', team: 'Alba Berlin', ht: 75, wt: 174, age: 20 },
  { rank: 41, name: 'Baba Miller', pos: 'PF', team: 'Cincinnati', ht: 84, wt: 208, age: 22 },
  { rank: 42, name: 'Flory Bidunga', pos: 'C', team: 'Kansas' },
  { rank: 43, name: 'Sergio de Larrea', pos: 'PG', team: 'Valencia', ht: 78, wt: 198, age: 20 },
  { rank: 44, name: 'Ryan Conwell', pos: 'SG', team: 'Louisville', ht: 75, wt: 215, age: 22 },
  { rank: 45, name: 'Trevon Brazile', pos: 'PF', team: 'Arkansas', ht: 83, wt: 226, age: 23 },
  { rank: 46, name: 'Braden Smith', pos: 'PG', team: 'Purdue', ht: 72, wt: 167, age: 22 },
  { rank: 47, name: 'Jeremy Fears Jr.', pos: 'PG', team: 'Michigan State' },
  { rank: 48, name: 'Rueben Chinyelu', pos: 'C', team: 'Florida' },
  { rank: 49, name: 'Felix Okpara', pos: 'C', team: 'Tennessee', ht: 83, wt: 237, age: 22 },
  { rank: 50, name: 'Andrej Stojakovic', pos: 'SG', team: 'Illinois' },
  { rank: 51, name: 'Jaden Bradley', pos: 'PG', team: 'Arizona', ht: 76, wt: 205, age: 22 },
  { rank: 52, name: 'Richie Saunders', pos: 'SG', team: 'BYU', ht: 78, wt: 205, age: 24 },
  { rank: 53, name: 'Billy Richmond III', pos: 'SG', team: 'Arkansas' },
  { rank: 54, name: "Ja'Kobi Gillespie", pos: 'PG', team: 'Tennessee', ht: 73, wt: 182, age: 22 },
  { rank: 55, name: 'Izaiyah Nelson', pos: 'PF', team: 'South Florida' },
  { rank: 56, name: 'Emanuel Sharp', pos: 'SG', team: 'Houston', ht: 76, wt: 208, age: 22 },
  { rank: 57, name: 'Nick Martinelli', pos: 'SF', team: 'Northwestern', ht: 80, wt: 224, age: 22 },
  { rank: 58, name: 'Kylan Boswell', pos: 'PG', team: 'Illinois', ht: 75, wt: 226, age: 21 },
  { rank: 59, name: 'Bruce Thornton', pos: 'PG', team: 'Ohio State', ht: 73, wt: 223, age: 22 },
  { rank: 60, name: 'Ugonna Onyenso', pos: 'C', team: 'Virginia', ht: 84, wt: 237, age: 21 },
];

// Stats par match de la saison universitaire/internationale 2025-26 (Tankathon),
// indexées par nom. { pts, reb, ast }.
export const PROSPECT_STATS = {
  'Cameron Boozer': { pts: 24.2, reb: 11.0, ast: 4.4 },
  'Darryn Peterson': { pts: 25.0, reb: 5.2, ast: 2.0 },
  'AJ Dybantsa': { pts: 26.4, reb: 7.1, ast: 3.8 },
  'Caleb Wilson': { pts: 22.8, reb: 10.8, ast: 3.1 },
  'Keaton Wagler': { pts: 19.0, reb: 5.4, ast: 4.5 },
  'Darius Acuff Jr.': { pts: 24.1, reb: 3.2, ast: 6.6 },
  'Kingston Flemings': { pts: 18.2, reb: 4.6, ast: 5.9 },
  'Brayden Burries': { pts: 19.4, reb: 5.9, ast: 2.9 },
  'Mikel Brown Jr.': { pts: 22.4, reb: 4.1, ast: 5.8 },
  'Nate Ament': { pts: 20.2, reb: 7.7, ast: 2.8 },
  'Labaron Philon Jr.': { pts: 25.6, reb: 4.1, ast: 5.8 },
  'Yaxel Lendeborg': { pts: 18.0, reb: 8.1, ast: 3.9 },
  'Karim Lopez': { pts: 16.8, reb: 8.5, ast: 2.7 },
  'Cameron Carr': { pts: 20.2, reb: 6.2, ast: 2.8 },
  'Hannes Steinbach': { pts: 19.3, reb: 12.2, ast: 1.6 },
  'Chris Cenac Jr.': { pts: 13.8, reb: 11.4, ast: 1.1 },
  'Morez Johnson Jr.': { pts: 18.8, reb: 10.5, ast: 1.7 },
  'Aday Mara': { pts: 18.6, reb: 10.4, ast: 3.7 },
  'Jayden Quaintance': { pts: 10.7, reb: 10.7, ast: 1.1 },
  'Bennett Stirtz': { pts: 18.9, reb: 2.5, ast: 4.2 },
  'Dailyn Swain': { pts: 19.0, reb: 8.3, ast: 3.9 },
  'Christian Anderson': { pts: 17.4, reb: 3.4, ast: 6.9 },
  'Allen Graves': { pts: 18.8, reb: 10.4, ast: 2.9 },
  'Ebuka Okorie': { pts: 23.8, reb: 3.7, ast: 3.7 },
  'Koa Peat': { pts: 18.3, reb: 7.3, ast: 3.3 },
  'Isaiah Evans': { pts: 19.2, reb: 4.1, ast: 1.6 },
  'Joshua Jefferson': { pts: 19.1, reb: 8.6, ast: 5.6 },
  'Meleek Thomas': { pts: 18.5, reb: 4.5, ast: 2.9 },
  'Henri Veesaar': { pts: 19.5, reb: 10.0, ast: 2.4 },
  'Tarris Reed Jr.': { pts: 19.4, reb: 11.8, ast: 3.0 },
  'Sergio de Larrea': { pts: 17.8, reb: 5.3, ast: 7.0 },
  'Alex Karaban': { pts: 13.8, reb: 5.5, ast: 2.5 },
  'Zuby Ejiofor': { pts: 19.6, reb: 8.8, ast: 4.3 },
  'Luigi Suigo': { pts: 16.9, reb: 10.6, ast: 1.7 },
  'Richie Saunders': { pts: 20.7, reb: 6.6, ast: 2.4 },
  'Ryan Conwell': { pts: 21.9, reb: 5.6, ast: 3.1 },
  'Ugonna Onyenso': { pts: 12.6, reb: 9.5, ast: 1.1 },
  'Jaden Bradley': { pts: 15.6, reb: 4.0, ast: 5.1 },
  'Trevon Brazile': { pts: 14.9, reb: 8.4, ast: 1.8 },
  'Baba Miller': { pts: 14.7, reb: 11.7, ast: 4.2 },
  'Jack Kayil': { pts: 21.1, reb: 4.9, ast: 6.2 },
  'Nick Martinelli': { pts: 23.3, reb: 6.3, ast: 2.0 },
  "Ja'Kobi Gillespie": { pts: 19.1, reb: 2.9, ast: 5.6 },
  'Emanuel Sharp': { pts: 18.9, reb: 3.6, ast: 2.1 },
  'Izaiyah Nelson': { pts: 20.9, reb: 12.6, ast: 1.6 },
  'Bruce Thornton': { pts: 19.6, reb: 5.0, ast: 3.9 },
  'Braden Smith': { pts: 14.9, reb: 3.7, ast: 9.2 },
  'Felix Okpara': { pts: 10.7, reb: 8.5, ast: 0.7 },
  'Kylan Boswell': { pts: 14.7, reb: 4.8, ast: 3.6 },
};
